---
name: Feature request
description: Suggest an idea for this project
body:
  - type: textarea
    id: project-suggestion
    attributes:
      label: Suggestion
      description: Please detail your suggestion for this project
    validations:
      required: true
