name: Localization
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: install
      run: |
        npm ci
    - name: Build
      run: |
        sh ./package/localization/deploy.sh
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.OAUTH_TOKEN }}
        directory: 'dist/local'
        repository: 'lolamtisch/MALSync-localization'
